package com.r3944realms.leashedplayer.content.blocks;

import com.r3944realms.leashedplayer.LeashedPlayer;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.registries.DeferredHolder;

public enum ModBlockResourceKeys {
    TEST_BLOCK(ModBlocksRegister.TEST_BLOCK)
    ;
    private final ResourceKey<Block> resourceKey;
    ModBlockResourceKeys(String name) {
        resourceKey = ResourceKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(LeashedPlayer.MOD_ID, name));
    }
    ModBlockResourceKeys(DeferredHolder<Block, ? extends Block> block) {
        resourceKey = ResourceKey.create(Registries.BLOCK, block.getId());
    }

    public ResourceKey<Block> getResourceKey() {
        return resourceKey;
    }
}

